export enum OperationType {
  SWAP_TRANSACTION = 'SWAP_TRANSACTION',
  DEPOSIT_TRANSACTION = 'DEPOSIT_TRANSACTION',
  WITHDRAWAL_TRANSACTION = 'WITHDRAWAL_TRANSACTION',
  BILL_PAYMENT_TRANSACTION = 'BILL_PAYMENT_TRANSACTION',
}